---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: pieterhertogh
spec:
  serviceAccountName: flux-reconciler
  interval: 10m
  targetNamespace: pieterhertogh
  chart:
    spec:
      chart: podinfo
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    # Default values for podinfo.
    replicaCount: 1
    logLevel: info
    ui:
      color: "#34577c"
      message: "This Helm Release is done with Flux"
      logo: ""

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: letsencrypt-production
      hosts:
        - host: pieterhertogh.test.funatic.nl
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-tls
          hosts:
            - pieterhertogh.test.funatic.nl
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: pieterhertogh
spec:
  acme:
    email: pieter.hertogh@funatic.nl
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
